sudo: required
dist: trusty

language: java
jdk:
- oraclejdk8

env:
  global:
    - CODECOV_TOKEN=d8f2c1f8-3ab1-4800-9871-bf9de95f9678

before_install:
  - echo "MAVEN_OPTS='-Xms1g -Xmx2g -XX:PermSize=512m -XX:MaxPermSize=1g'" > ~/.mavenrc

cache:
  directories:
  - $HOME/.m2/repository

install:
  - echo 'mvn clean install -B -V 1> .build.stdout 2> .build.stderr' > .build.sh
  - chmod 0755 .build.sh

script:
  - travis_wait 60 ./.build.sh

after_success:
  - tail -n  200 .build.stdout
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - tail -n  300 .build.stderr
  - tail -n 2000 .build.stdout

branches:
  except:
    - /^[0-9]/
