spring:
    application:
        name: confagrid

    datasource:
        username: embedded
        password: embedded
        driver-class-name: org.h2.Driver
        url: jdbc:h2:~/embeddedConfagridDb;DB_CLOSE_ON_EXIT=FALSE

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect

server:
    port: 8080